services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080

  redis:
    image: redis:latest
    ports:
      - "6379:6379"