name: JUnit Tests for Receitron

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Java config
        uses: actions/setup-java@v4
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn clean verify
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: target/surefire-reports
          retention-days: 14 
        
